"""initial schema

Revision ID: 2b92d5e11eaf
Revises: cbf39eee09ee
Create Date: 2026-03-06 18:34:58.774445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b92d5e11eaf'
down_revision: Union[str, Sequence[str], None] = 'cbf39eee09ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('name', sa.String(), nullable=True))
    op.add_column('lectures', sa.Column('teacher', sa.String(), nullable=True))
    op.add_column('lectures', sa.Column('subject', sa.String(), nullable=True))
    op.add_column('lectures', sa.Column('url', sa.String(), nullable=True))
    op.add_column('lectures', sa.Column('datetime', sa.String(), nullable=True))
    op.drop_index(op.f('ix_lectures_video_url'), table_name='lectures')
    op.create_index(op.f('ix_lectures_id'), 'lectures', ['id'], unique=False)
    op.create_unique_constraint(None, 'lectures', ['url'])
    op.drop_column('lectures', 'summary_id')
    op.drop_column('lectures', 'lecturer')
    op.drop_column('lectures', 'video_url')
    op.drop_column('lectures', 'lecture_date')
    op.drop_column('lectures', 'transcript_id')
    op.drop_column('lectures', 'presentation_id')
    op.drop_column('lectures', 'title')
    op.add_column('presentations', sa.Column('lecture_id', sa.Integer(), nullable=True))
    op.add_column('presentations', sa.Column('file_path', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'presentations', ['lecture_id'])
    op.create_foreign_key(None, 'presentations', 'lectures', ['lecture_id'], ['id'])
    op.drop_column('presentations', 'slide_timings')
    op.drop_column('presentations', 'presentation_path')
    op.create_unique_constraint(None, 'requests', ['lecture_id'])
    op.add_column('summaries', sa.Column('lecture_id', sa.Integer(), nullable=True))
    op.add_column('summaries', sa.Column('content', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'summaries', ['lecture_id'])
    op.create_foreign_key(None, 'summaries', 'lectures', ['lecture_id'], ['id'])
    op.drop_column('summaries', 'annotation')
    op.drop_column('summaries', 'summary_path')
    op.add_column('transcripts', sa.Column('lecture_id', sa.Integer(), nullable=True))
    op.add_column('transcripts', sa.Column('text', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'transcripts', ['lecture_id'])
    op.create_foreign_key(None, 'transcripts', 'lectures', ['lecture_id'], ['id'])
    op.drop_column('transcripts', 'audio_file')
    op.drop_column('transcripts', 'transcript_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('transcript_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transcripts', sa.Column('audio_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transcripts', type_='foreignkey')
    op.drop_constraint(None, 'transcripts', type_='unique')
    op.drop_column('transcripts', 'text')
    op.drop_column('transcripts', 'lecture_id')
    op.add_column('summaries', sa.Column('summary_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('summaries', sa.Column('annotation', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'summaries', type_='foreignkey')
    op.drop_constraint(None, 'summaries', type_='unique')
    op.drop_column('summaries', 'content')
    op.drop_column('summaries', 'lecture_id')
    op.drop_constraint(None, 'requests', type_='unique')
    op.add_column('presentations', sa.Column('presentation_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('presentations', sa.Column('slide_timings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'presentations', type_='foreignkey')
    op.drop_constraint(None, 'presentations', type_='unique')
    op.drop_column('presentations', 'file_path')
    op.drop_column('presentations', 'lecture_id')
    op.add_column('lectures', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lectures', sa.Column('presentation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lectures', sa.Column('transcript_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lectures', sa.Column('lecture_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('lectures', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lectures', sa.Column('lecturer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lectures', sa.Column('summary_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lectures', type_='unique')
    op.drop_index(op.f('ix_lectures_id'), table_name='lectures')
    op.create_index(op.f('ix_lectures_video_url'), 'lectures', ['video_url'], unique=True)
    op.drop_column('lectures', 'datetime')
    op.drop_column('lectures', 'url')
    op.drop_column('lectures', 'subject')
    op.drop_column('lectures', 'teacher')
    op.drop_column('lectures', 'name')
    # ### end Alembic commands ###
