"""initial schema

Revision ID: 74a3daf11971
Revises: c91ee0ead46c
Create Date: 2026-03-08 21:11:46.931723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a3daf11971'
down_revision: Union[str, Sequence[str], None] = 'c91ee0ead46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lectures', 'name')
    op.add_column('presentations', sa.Column('slides_timings', sa.JSON(), nullable=True))
    op.add_column('summaries', sa.Column('annotation', sa.Text(), nullable=True))
    op.add_column('summaries', sa.Column('summary_path', sa.String(), nullable=True))
    op.drop_column('summaries', 'content')
    op.add_column('transcripts', sa.Column('audio_path', sa.String(), nullable=True))
    op.add_column('transcripts', sa.Column('transcript_path', sa.String(), nullable=True))
    op.drop_column('transcripts', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('transcripts', 'transcript_path')
    op.drop_column('transcripts', 'audio_path')
    op.add_column('summaries', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('summaries', 'summary_path')
    op.drop_column('summaries', 'annotation')
    op.drop_column('presentations', 'slides_timings')
    op.add_column('lectures', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
