"""initial schema

Revision ID: cbda869b2109
Revises: 74a3daf11971
Create Date: 2026-03-08 21:35:04.539444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbda869b2109'
down_revision: Union[str, Sequence[str], None] = '74a3daf11971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentations', sa.Column('presentation_path', sa.String(), nullable=True))
    op.drop_column('presentations', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentations', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('presentations', 'presentation_path')
    # ### end Alembic commands ###
