"""initial schema

Revision ID: cbf39eee09ee
Revises: 
Create Date: 2026-03-06 17:47:59.503362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf39eee09ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('lecturer', sa.String(), nullable=False),
    sa.Column('lecture_date', sa.Date(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('summary_id', sa.Integer(), nullable=True),
    sa.Column('transcript_id', sa.Integer(), nullable=True),
    sa.Column('presentation_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lectures_video_url'), 'lectures', ['video_url'], unique=True)
    op.create_table('presentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slide_timings', sa.JSON(), nullable=True),
    sa.Column('presentation_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.Column('summary_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file', sa.String(), nullable=True),
    sa.Column('transcript_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('transcripts')
    op.drop_table('summaries')
    op.drop_table('presentations')
    op.drop_index(op.f('ix_lectures_video_url'), table_name='lectures')
    op.drop_table('lectures')
    # ### end Alembic commands ###
