"""initial schema

Revision ID: e99f2e06158c
Revises: df91c7556d1a
Create Date: 2026-03-13 00:57:28.483880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99f2e06158c'
down_revision: Union[str, Sequence[str], None] = 'df91c7556d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('presentations_lecture_id_fkey'), 'presentations', type_='foreignkey')
    op.create_foreign_key(None, 'presentations', 'lectures', ['lecture_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('requests_lecture_id_fkey'), 'requests', type_='foreignkey')
    op.create_foreign_key(None, 'requests', 'lectures', ['lecture_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('summaries_lecture_id_fkey'), 'summaries', type_='foreignkey')
    op.create_foreign_key(None, 'summaries', 'lectures', ['lecture_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('transcripts_lecture_id_fkey'), 'transcripts', type_='foreignkey')
    op.create_foreign_key(None, 'transcripts', 'lectures', ['lecture_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcripts', type_='foreignkey')
    op.create_foreign_key(op.f('transcripts_lecture_id_fkey'), 'transcripts', 'lectures', ['lecture_id'], ['id'])
    op.drop_constraint(None, 'summaries', type_='foreignkey')
    op.create_foreign_key(op.f('summaries_lecture_id_fkey'), 'summaries', 'lectures', ['lecture_id'], ['id'])
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.create_foreign_key(op.f('requests_lecture_id_fkey'), 'requests', 'lectures', ['lecture_id'], ['id'])
    op.drop_constraint(None, 'presentations', type_='foreignkey')
    op.create_foreign_key(op.f('presentations_lecture_id_fkey'), 'presentations', 'lectures', ['lecture_id'], ['id'])
    # ### end Alembic commands ###
